### ISSUE TITLE
Change tag policy for image

### ISSUE THREAD

**Issue by ketchoop** [php-censor/docker-php-censor#20]
For example php-censor:web -> to php-censor:web-0.9 where number is PHPCensor version.

**Comment by jaltek** [comment]
To catch this one up: It would be nice to have a tag which references the master version of php-censor, like php-censor-web:master or instead, as @ketchoop already mentioned an explicit tag for the releases of php-censor and an auto build hook @ Docker which triggers the build after each commit in the master branch of php-censor.

**Comment by ketchoop** [comment]
@corpsee Pls, pay attention to the comment above.

**Comment by corpsee** [comment]
@ketchoop @jaltek I made a note. Thanks!

**Comment by ptejada** [comment]
GitHub is working on an [Actions feature](https://github.com/features/actions/) which facilitates building and deploying docker images automatically. I made it to the open beta and is pretty cool.

One other automation service that I have used and recommend is https://buddy.works/

**Comment by corpsee** [comment]
@ptejada I already changed tag policy. Now we have 2 images: `php-censor-worker` and `php-censor-web` with version tags (like `1.0.0`), common `latest` and minor release latest (like `1.0-latest`).

See:
* https://hub.docker.com/r/phpcensor/php-censor-web/tags
* https://hub.docker.com/r/phpcensor/php-censor-worker/tags

I guess that is enough.

**Comment by corpsee** [comment]
@ptejada Do you have another point of view about image tags?

**Comment by ptejada** [comment]
@corpsee Did you tagged the images manually? My suggestion was to automate the process the images are updated and tagged.

**Comment by corpsee** [comment]
@ptejada No, automaticaly by DockerHub rules. if you khow how to make process better tell me. Thanks!

![dockerhub-rules](https://user-images.githubusercontent.com/1416706/51014359-cc1ad180-1599-11e9-8027-967c47beaad4.png)

**Comment by ptejada** [comment]
Sounds like you got it. Good to close?

**Comment by corpsee** [comment]
@ptejada Yes :)
