### ISSUE TITLE
hg build "Could not create a working copy"

### ISSUE THREAD

**Issue by spfuture** [php-censor/docker-php-censor#31]
it couldn't create /var/www/html/runtime/builds/18_df216\ build folder?
it is does not exist.

Args: ["hg clone %s \"%s\" -r %s","https:\/\/myip\/site\/","\/var\/www\/html\/runtime\/builds\/18_df216\/","prod"]
Command: hg clone https://myip/site/ "./" -r prod
abort: error: Try again

Execution status: 255
Failed to clone remote hg repository.
Exception: Could not create a working copy.

BUILD FAILED

**Comment by corpsee** [comment]
@spfuture Please see #21, may be it is connected problems. Can you check permitions on `runtime/builds` directory?

**Comment by spfuture** [comment]
Yes.
