### ISSUE TITLE
Server not found

### ISSUE THREAD

**Issue by frangte** [php-censor/docker-php-censor#36]
After using docker-composer, i visit localhost it auto redirect to `phpcensor.local/session/login` and server not found. Can you explain or help me.

**Comment by corpsee** [comment]
Hi @Frangte. See [web container documentation](https://github.com/php-censor/docker-php-censor/blob/master/web/README.md).

You should define your `SITE_URL` environment variable and add this host to `/etc/hosts` config on host OS (or only add default host `phpcensor.local` to `/etc/hosts`).

**Comment by frangte** [comment]
Thanks @corpsee, my issue has been resolved

**Comment by corpsee** [comment]
You are welcome!
