### ISSUE TITLE
Upgrade php version up to 7.1

### ISSUE THREAD

**Issue by frangte** [php-censor/docker-php-censor#38]
Hello!
I got an issue
 `This package requires php ^7.1.3 but your PHP version (7.0.15) does not satisfy that requirement.`
in my laravel project.
How to upgrade php in container.

Thanks so much!

**Comment by corpsee** [comment]
@Frangte I updated PHP version to 7.1.* in `latest` docker images of `phpcensor/php-censor-web` and `phpcensor/php-censor-worker`.

**Comment by frangte** [comment]
Thanks for information!!!
