### ISSUE TITLE
Add PostgreSQL as an DB variant

### ISSUE THREAD

**Issue by corpsee** [php-censor/docker-php-censor#5]
Would be great if PostgreSQL will be DB variant.

**Comment by ketchoop** [comment]
What do you mean? You can change db type by environment variables like ```docker run -e DB_TYPE=psql -e DB_HOST=psql_host ket4yii/php-censor```. Or just pass your own config by volume ```docker run -v ~/config.yml:/var/www/html/app/config.yml ket4yii/php-censor```(but now, I think, it doesn't work and this config will be rewrited by template).

There is ```type: $DB_TYPE``` in template for env substitution.

**Comment by corpsee** [comment]
I mean docker-compose file with PostgreSQL as storage instead of MySQL/MariaDB.

**Comment by ketchoop** [comment]
Ok. And I'm gonna do phpcensors and workers in the different containers. It's good for scalability, but I'm not sure that it's necessary. What do you think? It would be better if code of worker would be independent of phpcensor code(I mean, web part), but unfortunately we've got a lot of legacy from PHPCI and now it's not possible:disappointed:.

**Comment by corpsee** [comment]
I am not expert in the docker, but I think that will be great if every process will have separate container. But it doesn't matter on the practice.

The docker-compose file that I liked:
https://github.com/nouchka/docker-phpci/blob/master/docker-compose.yml

**Comment by ketchoop** [comment]
@corpsee added.
